# Author: Lianqing Zhang
# Date: 2022.07.26
# Version:2
# The purpose of this R script is to analyze hippocampal/amygdala subfields/subregions volume automatically,
# including linear model with input designs, generate tables and plots ready for publish.

source('functions.R')
# -------------------- 1.read inputs ------------------------
# inputs should include:
# 1 data, generated by hippocampal-qa pipeline, with id, volumes(generated 
#   automatically), clinical data(should already be merged previously)
# 2.filepath to design table


# set analysis settings
args <- commandArgs(trailingOnly=TRUE)

#group = 'Diagnosis'
group <- args[1]

#FilterStr = "Age>18"
FilterStr <- args[2]

#covariates = c("ICV","Age","Sex","Education")
covariates <- unlist(strsplit(args[3],"__"))
#x_list = c("HAMD_Total_17","HAMA_Total") #used for correlation analysis
x_list <- unlist(strsplit(args[4],"__"))
#inter_terms = c('Diagnosis*Age','Diagnosis*Sex','Diagnosis*Education')  # interaction terms
inter_terms <- unlist(strsplit(args[5],"__"))

#set data input and output
#out_dir = "D:/hmrrc/Lmri/SampleData/statisitcs"
out_dir <- args[6]
#data_path = ""
data_path <- args[7]

# config pic size and legend position
#pic_size_box = c(3,7) # width,height, should be less than 10, otherwise the front would be too small
pic_size_box <- as.numeric(unlist(strsplit(args[8],"__")))
#legend.position.box = "none"
legend.position.box <- args[9]
#BoxColorSetting = c("darkolivegreen4","darkorchid3")
BoxColorSetting <- args[10]
if (BoxColorSetting != "none"){BoxColorSetting <- unlist(strsplit(args[10],"__"))}
#pic_size_cor=c(7,3)  # width,height, should be less than 10, otherwise the front would be too small
pic_size_cor <- as.numeric(unlist(strsplit(args[11],"__")))
#legend.position.cor = "top"
legend.position.cor <- args[12]

################### should not change after this ###################

data = read.csv(data_path)
setwd(out_dir)

design = paste(c(group,covariates),collapse ="+")
interaction_ds = paste(c(design,inter_terms),collapse ="+")

# set log file
sink("log.txt",split = F)
print(paste0('Reading data from: ',data_path))
print(paste0("saving outputs to ",out_dir))

#subset data
print(paste0("using filter: ",FilterStr))

if (FilterStr != "none"){
  print(paste0("using filter: ",FilterStr))
  data=subset(data,eval(parse(text=FilterStr)))
  }

print("select QA passed data: QA=1")
data=subset(data,QA==1)

print(paste0("Analyzing GLM design: ",design,",with group:",group))



#generate AVG and AI
data[,all_scalar$AI] <- 100*(data[,all_scalar$lh]-data[,all_scalar$rh]) / (data[,all_scalar$lh]/2+data[,all_scalar$rh]/2)
data[,all_scalar$AVG] <- data[,all_scalar$lh]/2+data[,all_scalar$rh]/2

#transfer string to factor in data
data = transf_str2factor(data,c(group,covariates,x_list))

data = data[data[,group]!= 'NA',]
y_list = unlist(all_scalar,use.names=F)
# -------------- end of 1.read inputs ------------------------





## -------------------- 3.interaction ------------------------
print(" ")
print("start: interaction analysis")
if (inter_terms != "none"){
  print('testing interaction with design:')
  print(interaction_ds)
  out_int_res = lapply(flags_lst, Wrap_interaction,design=interaction_ds,data=data)
} else{
  print('test no interaction terms')
}

print("finished: interaction analysis ")
print(" ")

## ------------- end of 3.interaction ------------------------

## -------------------- 4.group difference ------------------------
print(" ")
print("start: MANCOVA analysis")
print("testing design:")
print(design)


MANCOVA = Do_MANCOVA(y_list,group,design,data)

#Do FDR
for (flag in flags_lst){MANCOVA = Do_FDR(flag,MANCOVA)}
MANCOVA[is.na(MANCOVA$P.FDR),'P.FDR'] = MANCOVA[is.na(MANCOVA$P.FDR),'p.value']

#prepare for printable output 
out_df_name = paste('MANCOVA','csv',sep = '.')

cols= sapply(levels(data[[group]]), function(x){paste('Mean(S.D.)',x)})
post_hoc_cols = colnames(MANCOVA)[grep('vs',colnames(MANCOVA))]
MANCOVA_out_df = MANCOVA[,c(cols,"F","EffectSize","p.value","P.FDR",post_hoc_cols)]
colnames(MANCOVA_out_df)[1:length(cols)] = sapply(levels(data[[group]]), function(x){
  n = MANCOVA[1,paste("n",x)]
  paste0(x, "\nMean(S.D)",'\n (n=',n,")")
  })

#prepare to drop post-hoc if p>=0.05
insig_p_rows = rownames(MANCOVA_out_df[MANCOVA_out_df$P.FDR>=0.05,])

for (pcol in c("p.value","P.FDR",post_hoc_cols)){
  MANCOVA_out_df = find_significance(MANCOVA_out_df,0.05,pcol)
}
if (length(post_hoc_cols)>0){
  MANCOVA_out_df[insig_p_rows,post_hoc_cols] = '-'
}

print(paste0('finished, saving outputs to ',out_df_name))
write.csv(as.matrix(MANCOVA_out_df),out_df_name)

#  Draw box plots
print("Draw box plots:")

BoxPlots=lapply(y_list,function(y_name){
  pic_name = paste("BoxPlot",y_name,"png",sep = '.')
  print(paste0("saving plot to ",pic_name))
  p_values = geneate_p_ls(MANCOVA[y_name,],data,group)
  box_p = Draw_boxplot(y_name=y_name,data=data,group=group,p_values =p_values)
  ggsave(pic_name,box_p,width = pic_size_box[1],height = pic_size_box[2])
  box_p
  })

print("finished: MANCOVA analysis")
print(" ")

## ------------- end of 4.group difference ------------------------

## -------------------- 4.partial correlation ------------------------
print(" ")
print("start: partial correlation analysis")
print("using covariates:")
print(paste(covariates,collapse = ', '))

print("1.Test partial correlation in the whole sample ... ")
out_df_flag = 'Whole'
ParCorr_Whole = lapply(x_list,function(x){
  sapply(y_list, Do_PartialCorr, x=x,covariates=covariates,in_data = data)
})
names(ParCorr_Whole) = x_list


WholeGroupPlots = lapply(x_list, function(x){
  lapply(y_list, function(y){
    out_p = Dw_cor_residual_whole_group(x,y,covariates,group,data,ParCorr_Whole)
    pic_name = paste("CorPlot.whole",paste0(x,'~',y),"png",sep = '.')
    ggsave(pic_name,out_p,width = pic_size_cor[1],height = pic_size_cor[2])
  })
})


print(" ")
print("2.Test partial correlation in each group ... ")


x_list_updated = update_covariates_lst(x_list)
gps = levels(data[[group]])
if (length(x_list_updated) >0){
  
  print("testing correlation variable with multiple levels...")
  
  # 2.Test partial correlation in each group ...
  ParCorr_by_group = lapply(gps, function(gp){
    print(paste0("Analyzing group: ",gp))
    data_gp = data[data[,group]==gp,]
    ParCorr = lapply(x_list_updated,function(x){
      sapply(y_list, Do_PartialCorr, x=x,covariates=covariates,in_data = data_gp)
    })
    names(ParCorr) = paste(x_list_updated,sep = '_')
    print("Done.")
    ParCorr
  })
  names(ParCorr_by_group) = gps
  

  # 3.Compare correlation coefficient differences between groups
  print(" ")
  print("3.Compare correlation coefficient differences between groups")
  
  
  if (length(gps) >2) {
    post_hoc_cols_sp = strsplit(post_hoc_cols,' vs ')
    post_hoc_corr =   lapply(post_hoc_cols_sp, function(post_hoc){
        sapply(x_list_updated, function(x){
          Wrap_Compare_Correlation(ParCorr_by_group[[post_hoc[1]]][[x]],ParCorr_by_group[[post_hoc[2]]][[x]])
        })
      })
    names(post_hoc_corr) = post_hoc_cols
    
  } else {
    #ToDo: test this after all is done
    post_hoc_corr = Wrap_Compare_Correlation(ParCorr_by_group[[1]][[x]],ParCorr_by_group[[2]][[x]])
    post_hoc_corr = c(post_hoc_corr)
    names(post_hoc_corr ) = paste(gps,collapse = ' vs ')
    
  }

    #ToDo: save
    #out_df_flag = paste(gps,collapse = '~')
    #out_p_name = paste('ParCorr',out_df_flag,flag,'p','csv',sep = '.')
    #write.csv(out_p,out_p_name)
  
} else{
  print("correlation variables only have 1 level, nothing to do.")
}


print("Drawing correlation plots with residuals")
print("x:")
print(paste(x_list,collapse = ', '))
print("y: volumes")

CorPlots = Wrap_Dw_cor_residual_by_group(x_list,unlist(all_scalar),covariates,group,data)
print("finished: partial correlation analysis")
print(" ")
## ------------- end of 4.partial correlation ------------------------